tasks:
  - name: check api env file
    command: if [ ! -f "api/.env" ]; then cp api/.env.example api/.env ; fi
  - name: bootstrap
    init: docker-compose pull
    command: docker-compose up

ports:
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-vscode.makefile-tools
