# tasks:
#   - name: Install frontend dependencies
#     init: cd client; yarn;
#     command: yarn dev

# ports:
#   - port: 3000
#     onOpen: open-preview

tasks:
  - name: check api env file
    init: if [ ! -f "api/.env" ]; then cp api/.env.example api/.env ; fi
    command: docker-compose up
  - name: bootstrap
    init: docker-compose pull
    command: docker-compose up

ports:
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-vscode.makefile-tools
