version: 2.1

jobs:
  hit-api-health:
    docker:
      # Primary container image where all steps run
      - image: cimg/base:2022.05
    steps:
      - run: |
          curl --request GET \
          --url 'https://docker-octane-vue.onrender.com/api/health'

workflows:
  my-workflow:
    jobs:
      - hit-api-healt: