version: 2.1
jobs:
  hit-api-health-endpoint:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - run:
          name: Hit health endpoint
          command: |
            curl --request GET \
            --url 'https://docker-octane-vue.onrender.com/api/health'
workflows:
  cron-api-health:
    jobs:
      - hit-api-health-endpoint
    triggers:
      - schedule:
          cron: "25 * * * *"
          filters:
            branches:
              only:
                - master