version: 2.1

jobs:
  hit-api-health:
    steps:
      - run: |
          curl --request GET \
          --url 'https://docker-octane-vue.onrender.com/api/health'

workflows:
  my-workflow:
    jobs:
      - hit-api-healt: