name: api-tests

defaults:
 run:
  working-directory: ./api

on:
  workflow_dispatch:
  
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ./api
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          working-directory: ./api
      - uses: "ramsey/composer-install@v2"
        with:
          working-directory: ./api
          composer-options: "--ignore-platform-reqs --optimize-autoloader"
      - name: run-tests
        run: php artisan test
