name: api-health-endpoint

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  health-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API health route
        run: |
          curl --request GET \
          --url 'https://docker-octane-vue.onrender.com/api/health'