name: api-deploy

on:
  workflow_dispatch:
  
jobs:
  Deploy API:
    runs-on: ubuntu-latest
    steps:
      - name: Triggering deploy hook
        run: |
          curl --request GET \
          --url env.ENV_DEPLOY_API_URL