
name: frontend-tests

defaults:
 run:
  working-directory: ./client

on:
  workflow_dispatch:
  
jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-tests
        run: yarn test
