name: playwright-tests

defaults:
  run:
    working-directory: ./client

on:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ./client
      - name: Build containers
        run: docker-compose -f "./../docker-compose-ci.yml" build
      - name: Install playwright dependencies
        run: docker-compose run playwright yarn
      - name: Up environment
        run: docker-compose -f "./../docker-compose-ci.yml" up --detach api client postgres
      - name: Wait
        run: sleep 5
      - name: Run tests
        run: docker-compose run playwright npx playwright test
      - name: Stop containers
        if: always()
        run: docker-compose -f "./../docker-compose-ci.yml" down
