name: playwright-tests

defaults:
  run:
    working-directory: ./client

on:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ./client
      - name: Build containers
        run: docker-compose -f "./../docker-compose-ci.yml" build
      # - name: Install client node_modules
      #   run: docker-compose run client yarn
      # - name: Install api composer
      #   run: docker-compose run api composer install --no-cache --ignore-platform-reqs
      # - name: Install playwright dependencies
      #   run: docker-compose run playwright yarn
      - name: Up environment
        run: docker-compose -f "./../docker-compose-ci.yml" up --detach
      - name: Run tests
        run: docker-compose run playwright npx playwright test
      - name: Stop containers
        if: always()
        run: docker-compose -f "./../docker-compose-ci.yml" down
